### ISSUE TITLE
Bug Report - no plot of the trajectory

### ISSUE THREAD

**Issue by tuffzinator** [mockingbirdnest/Principia#886]
FATAL log:

```
Log file created at: 2016/01/21 16:28:05
Running on machine: MICHA-PC
Log line format: [IWEF]mmdd hh:mm:ss.uuuuuu threadid file:line] msg
    @   55639399  	principia__SayHello [0x55639398+360744]
    @   5562456F  	principia__SayHello [0x5562456E+275198]
    @   55619EEA  	principia__SayHello [0x55619EE9+232569]
    @   5561B757  	principia__SayHello [0x5561B756+238822]
    @   55611F18  	principia__SayHello [0x55611F17+199847]
    @   5560F20C  	principia__SayHello [0x5560F20B+188315]
    @   556031B5  	principia__SayHello [0x556031B4+139076]
    @   555DF891  	principia__AdvanceTime [0x555DF890+80]
F0121 16:28:05.321233  3572 continuous_trajectory_body.hpp:346] Check failed: adjusted_tolerance_ < 1E6 * previous_adjusted_tolerance (+4.68287410098741093e+04 m vs. +1.00000000000000000e+03 m) Apocalypse occurred at +1.69560000000000000e+07 s, displacements are: {-3.49282603493174896e+10 m, +5.66270442741824417e+10 m, +1.43051734805826998e+09 m} {-3.49428985324578476e+10 m, +5.66261467240134583e+10 m, +1.43084853793783784e+09 m} {-3.49597231853022461e+10 m, +5.66240393730811310e+10 m, +1.43119247203491139e+09 m} {-3.49788863817104568e+10 m, +5.66196378825821075e+10 m, +1.43152237126945400e+09 m} {-3.49999793862095261e+10 m, +5.66107069127586975e+10 m, +1.43176777642360210e+09 m} {-3.50188619460542221e+10 m, +5.65935700674574738e+10 m, +1.43173955825286674e+09 m} {-3.50259985927999115e+10 m, +5.65730800483603821e+10 m, +1.43137054644079947e+09 m} {-3.50262614038773346e+10 m, +5.65595973268191986e+10 m, +1.43105020887789512e+09 m} {-3.50265505617097855e+10 m, +5.65518144973518982e+10 m, +1.43088812100199819e+09 m}, velocities are: {-5.03978634235681693e+03 m s^-1, -1.91513581246612659e+02 m s^-1, +1.18492526299651161e+02 m s^-1} {-5.81446760667980925e+03 m s^-1, -5.09221571312949607e+02 m s^-1, +1.26076469774440866e+02 m s^-1} {-6.65961692321701958e+03 m s^-1, -1.11486491197068221e+03 m s^-1, +1.27185009981394998e+02 m s^-1} {-7.52393606363402432e+03 m s^-1, -2.27493487743853575e+03 m s^-1, +1.13363830316464728e+02 m s^-1} {-7.90851250851699842e+03 m s^-1, -4.61011615100001836e+03 m s^-1, +5.69080769451357895e+01 m s^-1} {-5.19615554957706809e+03 m s^-1, -7.87950004670211638e+03 m s^-1, -9.07954216595477277e+01 m s^-1} {-6.82336758704137537e+02 m s^-1, -6.44296536649921109e+03 m s^-1, -1.46383434097063969e+02 m s^-1} {+8.47900445473596847e+01 m s^-1, -3.74178890429303920e+03 m s^-1, -8.78588688817521160e+01 m s^-1} {-3.71639892904535429e+02 m s^-1, -2.17278492760479230e+03 m s^-1, -3.48071394102201950e+01 m s^-1}
```

INFO log:
```
Log file created at: 2016/01/21 16:20:42
Running on machine: MICHA-PC
Log line format: [IWEF]mmdd hh:mm:ss.uuuuuu threadid file:line] msg
I0121 16:20:42.109884  3572 interface.cpp:225] Initialized Google logging for Principia
I0121 16:20:42.110883  3572 interface.cpp:226] Principia version 2015081515-Bourbaki-0-g6caa4a80b44ba7f9a030d79c558e4f8b1d051d6f built on 2015-08-15T13:55:56.6566908Z by Microsoft Visual C++ version 190023026 for Windows x86
I0121 16:20:42.110883  3572 interface.cpp:239] Base address is 555C0000
I0121 16:20:42.112884  3572 interface.cpp:287] principia.ksp_plugin_adapter.PrincipiaPluginAdapter.OnAwake()
W0121 16:20:42.155886  3572 interface.cpp:291] No principia state found, creating one
I0121 16:20:42.157886  3572 interface.cpp:313] Destroying Principia plugin
I0121 16:20:42.157886  3572 interface.cpp:319] Plugin destroyed
I0121 16:20:42.170887  3572 interface.cpp:304] Constructing Principia plugin
I0121 16:20:42.170887  3572 interface.cpp:308] Plugin constructed
I0121 16:20:42.170887  3572 interface.cpp:287] Inserting Eeloo...
I0121 16:20:42.170887  3572 plugin.cpp:82] Initial |{orbit.pos, orbit.vel}| for celestial at index 16: {{-1.98266950892634239e+10 m, -1.11161885595104568e+11 m, +1.19779159411380768e+10 m}, {+2.72143994428089036e+03 m s^-1, -4.80771720266853947e+02 m s^-1, +5.18022346039982367e+01 m s^-1}}
I0121 16:20:42.170887  3572 plugin.cpp:85] In barycentric coordinates: {{-7.24111297962967987e+10 m, +8.66411618622787933e+10 m, +1.19779159411380768e+10 m}, {-2.11758933472046965e+03 m s^-1, -1.77572301522902058e+03 m s^-1, +5.18022346039982367e+01 m s^-1}}
I0121 16:20:42.170887  3572 interface.cpp:287] Inserting Jool...
I0121 16:20:42.170887  3572 plugin.cpp:82] Initial |{orbit.pos, orbit.vel}| for celestial at index 8: {{-6.46630039934365845e+10 m, -9.47643060211173248e+09 m, +1.64220550901507288e+08 m}, {+6.06711691132437409e+02 m s^-1, -4.29562842878139782e+03 m s^-1, +9.82038459994681290e+01 m s^-1}}
I0121 16:20:42.170887  3572 plugin.cpp:85] In barycentric coordinates: {{+3.43048647196749268e+10 m, +5.56262804704452591e+10 m, +1.64220550901507288e+08 m}, {-3.68064333111439282e+03 m s^-1, +2.29638571312287786e+03 m s^-1, +9.82038459994681290e+01 m s^-1}}
I0121 16:20:42.170887  3572 interface.cpp:287] Inserting Pol...
I0121 16:20:42.170887  3572 plugin.cpp:82] Initial |{orbit.pos, orbit.vel}| for celestial at index 14: {{-1.32857179214623466e+08 m, -9.63172491794440895e+07 m, +1.21264469031588342e+07 m}, {+6.29199395442946411e+02 m s^-1, -1.21117643329424277e+03 m s^-1, +2.54774670323189838e+01 m s^-1}}
I0121 16:20:42.170887  3572 plugin.cpp:85] In barycentric coordinates: {{+1.16146368595781773e+07 m, +1.63686110495001435e+08 m, +1.21264469031588342e+07 m}, {-1.33225839648282499e+03 m s^-1, +2.96526216031810463e+02 m s^-1, +2.54774670323189838e+01 m s^-1}}
I0121 16:20:42.170887  3572 interface.cpp:287] Inserting Bop...
I0121 16:20:42.170887  3572 plugin.cpp:82] Initial |{orbit.pos, orbit.vel}| for celestial at index 11: {{-5.24561571064346656e+07 m, -9.81905117271706909e+07 m, +2.91893992529756464e+07 m}, {+1.24823256629345178e+03 m s^-1, -1.07379474672946549e+03 m s^-1, +5.41681500143781136e+00 m s^-1}}
I0121 16:20:42.170887  3572 plugin.cpp:85] In barycentric coordinates: {{-4.15007706580101997e+07 m, +1.03299133812485769e+08 m, +2.91893992529756464e+07 m}, {-1.62492127171869924e+03 m s^-1, -2.65989771185695190e+02 m s^-1, +5.41681500143781136e+00 m s^-1}}
I0121 16:20:42.170887  3572 interface.cpp:287] Inserting Tylo...
I0121 16:20:42.170887  3572 plugin.cpp:82] Initial |{orbit.pos, orbit.vel}| for celestial at index 12: {{+4.39470634374618456e+07 m, -5.25443204849147797e+07 m, +4.75638444149039969e+01 m}, {+1.55783165712095661e+03 m s^-1, +1.30294134735706098e+03 m s^-1, -8.86139884992065752e-01 m s^-1}}
I0121 16:20:42.170887  3572 plugin.cpp:85] In barycentric coordinates: {{-6.84999132641038895e+07 m, +1.09008293153397739e+05 m, +4.75638444149039969e+01 m}, {-3.23127424942094876e+00 m s^-1, -2.03088285862271846e+03 m s^-1, -8.86139884992065752e-01 m s^-1}}
I0121 16:20:42.170887  3572 interface.cpp:287] Inserting Vall...
I0121 16:20:42.170887  3572 plugin.cpp:82] Initial |{orbit.pos, orbit.vel}| for celestial at index 10: {{-4.31358834950585291e+07 m, -1.17926210010221717e+06 m, +0.00000000000000000e+00 m}, {+6.99276801962605248e+01 m s^-1, -2.55780862591912501e+03 m s^-1, +0.00000000000000000e+00 m s^-1}}
I0121 16:20:42.171887  3572 plugin.cpp:85] In barycentric coordinates: {{+2.68236339826892838e+07 m, +3.38021857867611423e+07 m, +0.00000000000000000e+00 m}, {-2.00435362564738898e+03 m s^-1, +1.59054751285149541e+03 m s^-1, +0.00000000000000000e+00 m s^-1}}
I0121 16:20:42.171887  3572 interface.cpp:287] Inserting Laythe...
I0121 16:20:42.171887  3572 plugin.cpp:82] Initial |{orbit.pos, orbit.vel}| for celestial at index 9: {{+1.74403219580207616e+07 m, -2.08519789468668588e+07 m, +0.00000000000000000e+00 m}, {+2.47290569961646406e+03 m s^-1, +2.06831090749424811e+03 m s^-1, +0.00000000000000000e+00 m s^-1}}
I0121 16:20:42.171887  3572 plugin.cpp:85] In barycentric coordinates: {{-2.71839657328822985e+07 m, +4.31628715575151145e+04 m, +0.00000000000000000e+00 m}, {-5.11501087659780751e+00 m s^-1, -3.22384032574800540e+03 m s^-1, +0.00000000000000000e+00 m s^-1}}
I0121 16:20:42.171887  3572 interface.cpp:287] Inserting Dres...
I0121 16:20:42.171887  3572 plugin.cpp:82] Initial |{orbit.pos, orbit.vel}| for celestial at index 15: {{+3.56483929294360886e+10 m, -2.99862979047452736e+10 m, -4.07549092339093876e+09 m}, {+2.98099261688861861e+03 m s^-1, +3.54247731022860489e+03 m s^-1, -5.67233136049468678e-01 m s^-1}}
I0121 16:20:42.171887  3572 plugin.cpp:85] In barycentric coordinates: {{-4.58851321832437057e+10 m, -8.03371800661762619e+09 m, -4.07549092339093876e+09 m}, {+7.97578311245777059e+02 m s^-1, -4.56062839012994846e+03 m s^-1, -5.67233136049468678e-01 m s^-1}}
I0121 16:20:42.171887  3572 interface.cpp:287] Inserting Duna...
I0121 16:20:42.171887  3572 plugin.cpp:82] Initial |{orbit.pos, orbit.vel}| for celestial at index 6: {{+1.74049038544730711e+09 m, +2.17135434797788849e+10 m, +3.28448759781371919e+04 m}, {-7.12367649271226310e+03 m s^-1, +5.71566569534194741e+02 m s^-1, -7.48386399762956955e+00 m s^-1}}
I0121 16:20:42.171887  3572 plugin.cpp:85] In barycentric coordinates: {{+1.55148687900252285e+10 m, -1.52903931819421844e+10 m, +3.28448759781371919e+04 m}, {+5.01682471666684341e+03 m s^-1, +5.08968809245429475e+03 m s^-1, -7.48386399762956955e+00 m s^-1}}
I0121 16:20:42.171887  3572 interface.cpp:287] Inserting Ike...
I0121 16:20:42.171887  3572 plugin.cpp:82] Initial |{orbit.pos, orbit.vel}| for celestial at index 7: {{-2.03236223212211812e+06 m, -2.49134262978152698e+06 m, +1.10245226578106340e+04 m}, {+2.30844962967039208e+02 m s^-1, -1.99992697128154930e+02 m s^-1, -1.68552541841562237e-01 m s^-1}}
I0121 16:20:42.171887  3572 plugin.cpp:85] In barycentric coordinates: {{-6.02121563842283562e+05 m, +3.15828022250706190e+06 m, +1.10245226578106340e+04 m}, {-3.01587275869552400e+02 m s^-1, -4.82865495291400464e+01 m s^-1, -1.68552541841562237e-01 m s^-1}}
I0121 16:20:42.171887  3572 interface.cpp:287] Inserting Kerbin...
I0121 16:20:42.171887  3572 plugin.cpp:82] Initial |{orbit.pos, orbit.vel}| for celestial at index 1: {{+8.72517426512010765e+09 m, -1.04320174957677250e+10 m, +0.00000000000000000e+00 m}, {+7.12185378164279155e+03 m s^-1, +5.95660574718599128e+03 m s^-1, +0.00000000000000000e+00 m s^-1}}
I0121 16:20:42.171887  3572 plugin.cpp:85] In barycentric coordinates: {{-1.35998230778619442e+10 m, +2.16157251062698364e+07 m, +0.00000000000000000e+00 m}, {-1.47568777781725657e+01 m s^-1, -9.28448897619395939e+03 m s^-1, +0.00000000000000000e+00 m s^-1}}
I0121 16:20:42.171887  3572 interface.cpp:287] Inserting Minmus...
I0121 16:20:42.171887  3572 plugin.cpp:82] Initial |{orbit.pos, orbit.vel}| for celestial at index 3: {{+2.16292189894211143e+07 m, -4.14372090562018380e+07 m, +4.91269697216193005e+06 m}, {+2.42994235383725993e+02 m s^-1, +1.26862839492331275e+02 m s^-1, +2.16928873744737294e-01 m s^-1}}
I0121 16:20:42.171887  3572 plugin.cpp:85] In barycentric coordinates: {{-4.56458003312897384e+07 m, +1.00660975842547789e+07 m, +4.91269697216193005e+06 m}, {-5.90094452029064769e+01 m s^-1, -2.67690612182466850e+02 m s^-1, +2.16928873744737294e-01 m s^-1}}
I0121 16:20:42.171887  3572 interface.cpp:287] Inserting Mun...
I0121 16:20:42.171887  3572 plugin.cpp:82] Initial |{orbit.pos, orbit.vel}| for celestial at index 2: {{-8.12207565447380953e+06 m, -8.83356593132149801e+06 m, +0.00000000000000000e+00 m}, {+3.99346718664974048e+02 m s^-1, -3.67181424219033829e+02 m s^-1, +0.00000000000000000e+00 m s^-1}}
I0121 16:20:42.171887  3572 plugin.cpp:85] In barycentric coordinates: {{-1.54620852842161339e+06 m, +1.18999680330090113e+07 m, +0.00000000000000000e+00 m}, {-5.37971977524251315e+02 m s^-1, -6.99010114279213894e+01 m s^-1, +0.00000000000000000e+00 m s^-1}}
I0121 16:20:42.171887  3572 interface.cpp:287] Inserting Eve...
I0121 16:20:42.171887  3572 plugin.cpp:82] Initial |{orbit.pos, orbit.vel}| for celestial at index 5: {{+8.12607669819884205e+09 m, -5.70892826353357029e+09 m, +5.68079144028352224e+05 m}, {+6.21050186610365199e+03 m s^-1, +8.83967999498287099e+03 m s^-1, -3.96136793953146366e+02 m s^-1}}
I0121 16:20:42.171887  3572 plugin.cpp:85] In barycentric coordinates: {{-9.59661829271801758e+09 m, -2.55536724700238800e+09 m, +5.68079144028352224e+05 m}, {+2.77961903381649972e+03 m s^-1, -1.04395399261376624e+04 m s^-1, -3.96136793953146366e+02 m s^-1}}
I0121 16:20:42.171887  3572 interface.cpp:287] Inserting Gilly...
I0121 16:20:42.171887  3572 plugin.cpp:82] Initial |{orbit.pos, orbit.vel}| for celestial at index 13: {{+2.67836337704155594e+07 m, -1.09430679210215993e+07 m, +4.86088829692997690e+06 m}, {+4.52691582600576112e+02 m s^-1, +3.04392124086301919e+02 m s^-1, -7.92175063641671162e+00 m s^-1}}
I0121 16:20:42.171887  3572 plugin.cpp:85] In barycentric coordinates: {{-2.55989804212713093e+07 m, -1.34835445956619699e+07 m, +4.86088829692997690e+06 m}, {-5.78032706040074231e+01 m s^-1, -5.42441716749979378e+02 m s^-1, -7.92175063641671162e+00 m s^-1}}
I0121 16:20:42.171887  3572 interface.cpp:287] Inserting Moho...
I0121 16:20:42.171887  3572 plugin.cpp:82] Initial |{orbit.pos, orbit.vel}| for celestial at index 4: {{+5.18166680370298290e+09 m, +3.60553076074980640e+09 m, -1.98406858522129059e+08 m}, {-6.94593767681264944e+03 m s^-1, +9.90912753813066411e+03 m s^-1, -1.43500343556567805e+03 m s^-1}}
I0121 16:20:42.171887  3572 plugin.cpp:85] In barycentric coordinates: {{-5.68675304032700539e+08 m, -6.28698109826122189e+09 m, -1.98406858522129059e+08 m}, {+1.20556012859314724e+04 m s^-1, -1.04849244716043177e+03 m s^-1, -1.43500343556567805e+03 m s^-1}}
I0121 16:20:45.320067  3572 interface.cpp:644] principia::ksp_plugin::principia__SerializePlugin
I0121 16:20:45.321068  3572 plugin.cpp:477] principia::ksp_plugin::Plugin::WriteToMessage
I0121 16:20:45.321068  3572 ephemeris_body.hpp:362] principia::physics::Ephemeris<class principia::geometry::Frame<enum principia::serialization::Frame_PluginTag,7,1> >::WriteToMessage
I0121 16:20:45.321068  3572 continuous_trajectory_body.hpp:201] principia::physics::ContinuousTrajectory<class principia::geometry::Frame<enum principia::serialization::Frame_PluginTag,7,1> >::WriteToMessage
I0121 16:20:45.321068  3572 continuous_trajectory_body.hpp:224] this: 129D6A68
I0121 16:20:45.321068  3572 continuous_trajectory_body.hpp:225] message->SpaceUsed(): 2724
I0121 16:20:45.321068  3572 continuous_trajectory_body.hpp:226] message->ByteSize(): 561
I0121 16:20:45.321068  3572 continuous_trajectory_body.hpp:201] principia::physics::ContinuousTrajectory<class principia::geometry::Frame<enum principia::serialization::Frame_PluginTag,7,1> >::WriteToMessage
I0121 16:20:45.321068  3572 continuous_trajectory_body.hpp:224] this: 129D6AB0
I0121 16:20:45.321068  3572 continuous_trajectory_body.hpp:225] message->SpaceUsed(): 3988
I0121 16:20:45.321068  3572 continuous_trajectory_body.hpp:226] message->ByteSize(): 809
I0121 16:20:45.321068  3572 continuous_trajectory_body.hpp:201] principia::physics::ContinuousTrajectory<class principia::geometry::Frame<enum principia::serialization::Frame_PluginTag,7,1> >::WriteToMessage
I0121 16:20:45.321068  3572 continuous_trajectory_body.hpp:224] this: 129D6AF8
I0121 16:20:45.321068  3572 continuous_trajectory_body.hpp:225] message->SpaceUsed(): 4604
I0121 16:20:45.321068  3572 continuous_trajectory_body.hpp:226] message->ByteSize(): 933
I0121 16:20:45.321068  3572 continuous_trajectory_body.hpp:201] principia::physics::ContinuousTrajectory<class principia::geometry::Frame<enum principia::serialization::Frame_PluginTag,7,1> >::WriteToMessage
I0121 16:20:45.321068  3572 continuous_trajectory_body.hpp:224] this: 129D6B40
I0121 16:20:45.321068  3572 continuous_trajectory_body.hpp:225] message->SpaceUsed(): 3988
I0121 16:20:45.321068  3572 continuous_trajectory_body.hpp:226] message->ByteSize(): 809
I0121 16:20:45.321068  3572 continuous_trajectory_body.hpp:201] principia::physics::ContinuousTrajectory<class principia::geometry::Frame<enum principia::serialization::Frame_PluginTag,7,1> >::WriteToMessage
I0121 16:20:45.321068  3572 continuous_trajectory_body.hpp:224] this: 129D6240
I0121 16:20:45.322067  3572 continuous_trajectory_body.hpp:225] message->SpaceUsed(): 3340
I0121 16:20:45.322067  3572 continuous_trajectory_body.hpp:226] message->ByteSize(): 685
I0121 16:20:45.322067  3572 continuous_trajectory_body.hpp:201] principia::physics::ContinuousTrajectory<class principia::geometry::Frame<enum principia::serialization::Frame_PluginTag,7,1> >::WriteToMessage
I0121 16:20:45.322067  3572 continuous_trajectory_body.hpp:224] this: 129D6480
I0121 16:20:45.322067  3572 continuous_trajectory_body.hpp:225] message->SpaceUsed(): 3340
I0121 16:20:45.322067  3572 continuous_trajectory_body.hpp:226] message->ByteSize(): 685
I0121 16:20:45.322067  3572 continuous_trajectory_body.hpp:201] principia::physics::ContinuousTrajectory<class principia::geometry::Frame<enum principia::serialization::Frame_PluginTag,7,1> >::WriteToMessage
I0121 16:20:45.322067  3572 continuous_trajectory_body.hpp:224] this: 129D63F0
I0121 16:20:45.322067  3572 continuous_trajectory_body.hpp:225] message->SpaceUsed(): 5220
I0121 16:20:45.322067  3572 continuous_trajectory_body.hpp:226] message->ByteSize(): 1057
I0121 16:20:45.322067  3572 continuous_trajectory_body.hpp:201] principia::physics::ContinuousTrajectory<class principia::geometry::Frame<enum principia::serialization::Frame_PluginTag,7,1> >::WriteToMessage
I0121 16:20:45.322067  3572 continuous_trajectory_body.hpp:224] this: 129D65A0
I0121 16:20:45.322067  3572 continuous_trajectory_body.hpp:225] message->SpaceUsed(): 5220
I0121 16:20:45.322067  3572 continuous_trajectory_body.hpp:226] message->ByteSize(): 1057
I0121 16:20:45.322067  3572 continuous_trajectory_body.hpp:201] principia::physics::ContinuousTrajectory<class principia::geometry::Frame<enum principia::serialization::Frame_PluginTag,7,1> >::WriteToMessage
I0121 16:20:45.322067  3572 continuous_trajectory_body.hpp:224] this: 129D6BD0
I0121 16:20:45.322067  3572 continuous_trajectory_body.hpp:225] message->SpaceUsed(): 5220
I0121 16:20:45.322067  3572 continuous_trajectory_body.hpp:226] message->ByteSize(): 1057
I0121 16:20:45.322067  3572 continuous_trajectory_body.hpp:201] principia::physics::ContinuousTrajectory<class principia::geometry::Frame<enum principia::serialization::Frame_PluginTag,7,1> >::WriteToMessage
I0121 16:20:45.322067  3572 continuous_trajectory_body.hpp:224] this: 129D6C18
I0121 16:20:45.322067  3572 continuous_trajectory_body.hpp:225] message->SpaceUsed(): 5220
I0121 16:20:45.322067  3572 continuous_trajectory_body.hpp:226] message->ByteSize(): 1057
I0121 16:20:45.322067  3572 continuous_trajectory_body.hpp:201] principia::physics::ContinuousTrajectory<class principia::geometry::Frame<enum principia::serialization::Frame_PluginTag,7,1> >::WriteToMessage
I0121 16:20:45.322067  3572 continuous_trajectory_body.hpp:224] this: 129D6C60
I0121 16:20:45.322067  3572 continuous_trajectory_body.hpp:225] message->SpaceUsed(): 4912
I0121 16:20:45.322067  3572 continuous_trajectory_body.hpp:226] message->ByteSize(): 995
I0121 16:20:45.322067  3572 continuous_trajectory_body.hpp:201] principia::physics::ContinuousTrajectory<class principia::geometry::Frame<enum principia::serialization::Frame_PluginTag,7,1> >::WriteToMessage
I0121 16:20:45.322067  3572 continuous_trajectory_body.hpp:224] this: 129D6CA8
I0121 16:20:45.322067  3572 continuous_trajectory_body.hpp:225] message->SpaceUsed(): 4604
I0121 16:20:45.322067  3572 continuous_trajectory_body.hpp:226] message->ByteSize(): 933
I0121 16:20:45.322067  3572 continuous_trajectory_body.hpp:201] principia::physics::ContinuousTrajectory<class principia::geometry::Frame<enum principia::serialization::Frame_PluginTag,7,1> >::WriteToMessage
I0121 16:20:45.322067  3572 continuous_trajectory_body.hpp:224] this: 129D6CF0
I0121 16:20:45.322067  3572 continuous_trajectory_body.hpp:225] message->SpaceUsed(): 5528
I0121 16:20:45.322067  3572 continuous_trajectory_body.hpp:226] message->ByteSize(): 1119
I0121 16:20:45.322067  3572 continuous_trajectory_body.hpp:201] principia::physics::ContinuousTrajectory<class principia::geometry::Frame<enum principia::serialization::Frame_PluginTag,7,1> >::WriteToMessage
I0121 16:20:45.322067  3572 continuous_trajectory_body.hpp:224] this: 129D6D38
I0121 16:20:45.322067  3572 continuous_trajectory_body.hpp:225] message->SpaceUsed(): 4296
I0121 16:20:45.322067  3572 continuous_trajectory_body.hpp:226] message->ByteSize(): 871
I0121 16:20:45.322067  3572 continuous_trajectory_body.hpp:201] principia::physics::ContinuousTrajectory<class principia::geometry::Frame<enum principia::serialization::Frame_PluginTag,7,1> >::WriteToMessage
I0121 16:20:45.322067  3572 continuous_trajectory_body.hpp:224] this: 129D6D80
I0121 16:20:45.322067  3572 continuous_trajectory_body.hpp:225] message->SpaceUsed(): 4296
I0121 16:20:45.322067  3572 continuous_trajectory_body.hpp:226] message->ByteSize(): 871
I0121 16:20:45.322067  3572 continuous_trajectory_body.hpp:201] principia::physics::ContinuousTrajectory<class principia::geometry::Frame<enum principia::serialization::Frame_PluginTag,7,1> >::WriteToMessage
I0121 16:20:45.322067  3572 continuous_trajectory_body.hpp:224] this: 129D6DC8
I0121 16:20:45.322067  3572 continuous_trajectory_body.hpp:225] message->SpaceUsed(): 2724
I0121 16:20:45.322067  3572 continuous_trajectory_body.hpp:226] message->ByteSize(): 561
I0121 16:20:45.322067  3572 continuous_trajectory_body.hpp:201] principia::physics::ContinuousTrajectory<class principia::geometry::Frame<enum principia::serialization::Frame_PluginTag,7,1> >::WriteToMessage
I0121 16:20:45.322067  3572 continuous_trajectory_body.hpp:224] this: 129D6E10
I0121 16:20:45.322067  3572 continuous_trajectory_body.hpp:225] message->SpaceUsed(): 2724
I0121 16:20:45.322067  3572 continuous_trajectory_body.hpp:226] message->ByteSize(): 561
I0121 16:20:45.322067  3572 ephemeris_body.hpp:377] message->SpaceUsed(): 95548
I0121 16:20:45.322067  3572 ephemeris_body.hpp:378] message->ByteSize(): 19570
I0121 16:20:45.322067  3572 physics_bubble.cpp:219] principia::ksp_plugin::PhysicsBubble::WriteToMessage
I0121 16:20:45.322067  3572 physics_bubble.cpp:266] message->SpaceUsed(): 40
I0121 16:20:45.323067  3572 physics_bubble.cpp:267] message->ByteSize(): 2
I0121 16:20:45.323067  3572 plugin.cpp:526] message->SpaceUsed(): 96348
I0121 16:20:45.323067  3572 plugin.cpp:527] message->ByteSize(): 19722
I0121 16:20:45.324067  3572 interface.cpp:676] principia::ksp_plugin::principia__DeletePluginSerialization
I0121 16:20:45.324067  3572 interface.cpp:644] principia::ksp_plugin::principia__SerializePlugin
I0121 16:20:45.324067  3572 interface.cpp:676] principia::ksp_plugin::principia__DeletePluginSerialization
I0121 16:20:54.492591  3572 interface.cpp:644] principia::ksp_plugin::principia__SerializePlugin
I0121 16:20:54.492591  3572 plugin.cpp:477] principia::ksp_plugin::Plugin::WriteToMessage
I0121 16:20:54.492591  3572 ephemeris_body.hpp:362] principia::physics::Ephemeris<class principia::geometry::Frame<enum principia::serialization::Frame_PluginTag,7,1> >::WriteToMessage
I0121 16:20:54.492591  3572 continuous_trajectory_body.hpp:201] principia::physics::ContinuousTrajectory<class principia::geometry::Frame<enum principia::serialization::Frame_PluginTag,7,1> >::WriteToMessage
I0121 16:20:54.492591  3572 continuous_trajectory_body.hpp:224] this: 129D6A68
I0121 16:20:54.492591  3572 continuous_trajectory_body.hpp:225] message->SpaceUsed(): 2724
I0121 16:20:54.492591  3572 continuous_trajectory_body.hpp:226] message->ByteSize(): 561
I0121 16:20:54.492591  3572 continuous_trajectory_body.hpp:201] principia::physics::ContinuousTrajectory<class principia::geometry::Frame<enum principia::serialization::Frame_PluginTag,7,1> >::WriteToMessage
I0121 16:20:54.492591  3572 continuous_trajectory_body.hpp:224] this: 129D6AB0
I0121 16:20:54.492591  3572 continuous_trajectory_body.hpp:225] message->SpaceUsed(): 3988
I0121 16:20:54.492591  3572 continuous_trajectory_body.hpp:226] message->ByteSize(): 809
I0121 16:20:54.492591  3572 continuous_trajectory_body.hpp:201] principia::physics::ContinuousTrajectory<class principia::geometry::Frame<enum principia::serialization::Frame_PluginTag,7,1> >::WriteToMessage
I0121 16:20:54.492591  3572 continuous_trajectory_body.hpp:224] this: 129D6AF8
I0121 16:20:54.492591  3572 continuous_trajectory_body.hpp:225] message->SpaceUsed(): 4604
I0121 16:20:54.492591  3572 continuous_trajectory_body.hpp:226] message->ByteSize(): 933
I0121 16:20:54.492591  3572 continuous_trajectory_body.hpp:201] principia::physics::ContinuousTrajectory<class principia::geometry::Frame<enum principia::serialization::Frame_PluginTag,7,1> >::WriteToMessage
I0121 16:20:54.492591  3572 continuous_trajectory_body.hpp:224] this: 129D6B40
I0121 16:20:54.492591  3572 continuous_trajectory_body.hpp:225] message->SpaceUsed(): 3988
I0121 16:20:54.492591  3572 continuous_trajectory_body.hpp:226] message->ByteSize(): 809
I0121 16:20:54.492591  3572 continuous_trajectory_body.hpp:201] principia::physics::ContinuousTrajectory<class principia::geometry::Frame<enum principia::serialization::Frame_PluginTag,7,1> >::WriteToMessage
I0121 16:20:54.492591  3572 continuous_trajectory_body.hpp:224] this: 129D6240
I0121 16:20:54.492591  3572 continuous_trajectory_body.hpp:225] message->SpaceUsed(): 3340
I0121 16:20:54.492591  3572 continuous_trajectory_body.hpp:226] message->ByteSize(): 685
I0121 16:20:54.492591  3572 continuous_trajectory_body.hpp:201] principia::physics::ContinuousTrajectory<class principia::geometry::Frame<enum principia::serialization::Frame_PluginTag,7,1> >::WriteToMessage
I0121 16:20:54.492591  3572 continuous_trajectory_body.hpp:224] this: 129D6480
I0121 16:20:54.492591  3572 continuous_trajectory_body.hpp:225] message->SpaceUsed(): 3340
I0121 16:20:54.492591  3572 continuous_trajectory_body.hpp:226] message->ByteSize(): 685
I0121 16:20:54.492591  3572 continuous_trajectory_body.hpp:201] principia::physics::ContinuousTrajectory<class principia::geometry::Frame<enum principia::serialization::Frame_PluginTag,7,1> >::WriteToMessage
I0121 16:20:54.492591  3572 continuous_trajectory_body.hpp:224] this: 129D63F0
I0121 16:20:54.492591  3572 continuous_trajectory_body.hpp:225] message->SpaceUsed(): 5220
I0121 16:20:54.492591  3572 continuous_trajectory_body.hpp:226] message->ByteSize(): 1057
I0121 16:20:54.492591  3572 continuous_trajectory_body.hpp:201] principia::physics::ContinuousTrajectory<class principia::geometry::Frame<enum principia::serialization::Frame_PluginTag,7,1> >::WriteToMessage
I0121 16:20:54.492591  3572 continuous_trajectory_body.hpp:224] this: 129D65A0
I0121 16:20:54.492591  3572 continuous_trajectory_body.hpp:225] message->SpaceUsed(): 5220
I0121 16:20:54.492591  3572 continuous_trajectory_body.hpp:226] message->ByteSize(): 1057
I0121 16:20:54.492591  3572 continuous_trajectory_body.hpp:201] principia::physics::ContinuousTrajectory<class principia::geometry::Frame<enum principia::serialization::Frame_PluginTag,7,1> >::WriteToMessage
I0121 16:20:54.492591  3572 continuous_trajectory_body.hpp:224] this: 129D6BD0
I0121 16:20:54.492591  3572 continuous_trajectory_body.hpp:225] message->SpaceUsed(): 5220
I0121 16:20:54.492591  3572 continuous_trajectory_body.hpp:226] message->ByteSize(): 1057
I0121 16:20:54.493592  3572 continuous_trajectory_body.hpp:201] principia::physics::ContinuousTrajectory<class principia::geometry::Frame<enum principia::serialization::Frame_PluginTag,7,1> >::WriteToMessage
I0121 16:20:54.493592  3572 continuous_trajectory_body.hpp:224] this: 129D6C18
I0121 16:20:54.493592  3572 continuous_trajectory_body.hpp:225] message->SpaceUsed(): 5220
I0121 16:20:54.493592  3572 continuous_trajectory_body.hpp:226] message->ByteSize(): 1057
I0121 16:20:54.493592  3572 continuous_trajectory_body.hpp:201] principia::physics::ContinuousTrajectory<class principia::geometry::Frame<enum principia::serialization::Frame_PluginTag,7,1> >::WriteToMessage
I0121 16:20:54.493592  3572 continuous_trajectory_body.hpp:224] this: 129D6C60
I0121 16:20:54.493592  3572 continuous_trajectory_body.hpp:225] message->SpaceUsed(): 4912
I0121 16:20:54.493592  3572 continuous_trajectory_body.hpp:226] message->ByteSize(): 995
I0121 16:20:54.493592  3572 continuous_trajectory_body.hpp:201] principia::physics::ContinuousTrajectory<class principia::geometry::Frame<enum principia::serialization::Frame_PluginTag,7,1> >::WriteToMessage
I0121 16:20:54.493592  3572 continuous_trajectory_body.hpp:224] this: 129D6CA8
I0121 16:20:54.493592  3572 continuous_trajectory_body.hpp:225] message->SpaceUsed(): 4604
I0121 16:20:54.493592  3572 continuous_trajectory_body.hpp:226] message->ByteSize(): 933
I0121 16:20:54.493592  3572 continuous_trajectory_body.hpp:201] principia::physics::ContinuousTrajectory<class principia::geometry::Frame<enum principia::serialization::Frame_PluginTag,7,1> >::WriteToMessage
I0121 16:20:54.493592  3572 continuous_trajectory_body.hpp:224] this: 129D6CF0
I0121 16:20:54.493592  3572 continuous_trajectory_body.hpp:225] message->SpaceUsed(): 5528
I0121 16:20:54.493592  3572 continuous_trajectory_body.hpp:226] message->ByteSize(): 1119
I0121 16:20:54.493592  3572 continuous_trajectory_body.hpp:201] principia::physics::ContinuousTrajectory<class principia::geometry::Frame<enum principia::serialization::Frame_PluginTag,7,1> >::WriteToMessage
I0121 16:20:54.493592  3572 continuous_trajectory_body.hpp:224] this: 129D6D38
I0121 16:20:54.493592  3572 continuous_trajectory_body.hpp:225] message->SpaceUsed(): 4296
I0121 16:20:54.493592  3572 continuous_trajectory_body.hpp:226] message->ByteSize(): 871
I0121 16:20:54.493592  3572 continuous_trajectory_body.hpp:201] principia::physics::ContinuousTrajectory<class principia::geometry::Frame<enum principia::serialization::Frame_PluginTag,7,1> >::WriteToMessage
I0121 16:20:54.493592  3572 continuous_trajectory_body.hpp:224] this: 129D6D80
I0121 16:20:54.493592  3572 continuous_trajectory_body.hpp:225] message->SpaceUsed(): 4296
I0121 16:20:54.493592  3572 continuous_trajectory_body.hpp:226] message->ByteSize(): 871
I0121 16:20:54.493592  3572 continuous_trajectory_body.hpp:201] principia::physics::ContinuousTrajectory<class principia::geometry::Frame<enum principia::serialization::Frame_PluginTag,7,1> >::WriteToMessage
I0121 16:20:54.493592  3572 continuous_trajectory_body.hpp:224] this: 129D6DC8
I0121 16:20:54.493592  3572 continuous_trajectory_body.hpp:225] message->SpaceUsed(): 2724
I0121 16:20:54.493592  3572 continuous_trajectory_body.hpp:226] message->ByteSize(): 561
I0121 16:20:54.493592  3572 continuous_trajectory_body.hpp:201] principia::physics::ContinuousTrajectory<class principia::geometry::Frame<enum principia::serialization::Frame_PluginTag,7,1> >::WriteToMessage
I0121 16:20:54.493592  3572 continuous_trajectory_body.hpp:224] this: 129D6E10
I0121 16:20:54.493592  3572 continuous_trajectory_body.hpp:225] message->SpaceUsed(): 2724
I0121 16:20:54.493592  3572 continuous_trajectory_body.hpp:226] message->ByteSize(): 561
I0121 16:20:54.493592  3572 ephemeris_body.hpp:377] message->SpaceUsed(): 95548
I0121 16:20:54.493592  3572 ephemeris_body.hpp:378] message->ByteSize(): 19570
I0121 16:20:54.493592  3572 physics_bubble.cpp:219] principia::ksp_plugin::PhysicsBubble::WriteToMessage
I0121 16:20:54.493592  3572 physics_bubble.cpp:266] message->SpaceUsed(): 40
I0121 16:20:54.493592  3572 physics_bubble.cpp:267] message->ByteSize(): 2
I0121 16:20:54.493592  3572 plugin.cpp:526] message->SpaceUsed(): 96348
I0121 16:20:54.493592  3572 plugin.cpp:527] message->ByteSize(): 19722
I0121 16:20:54.494591  3572 interface.cpp:676] principia::ksp_plugin::principia__DeletePluginSerialization
I0121 16:20:54.494591  3572 interface.cpp:644] principia::ksp_plugin::principia__SerializePlugin
I0121 16:20:54.494591  3572 interface.cpp:676] principia::ksp_plugin::principia__DeletePluginSerialization
I0121 16:20:56.725719  3572 interface.cpp:644] principia::ksp_plugin::principia__SerializePlugin
I0121 16:20:56.725719  3572 plugin.cpp:477] principia::ksp_plugin::Plugin::WriteToMessage
I0121 16:20:56.725719  3572 ephemeris_body.hpp:362] principia::physics::Ephemeris<class principia::geometry::Frame<enum principia::serialization::Frame_PluginTag,7,1> >::WriteToMessage
I0121 16:20:56.725719  3572 continuous_trajectory_body.hpp:201] principia::physics::ContinuousTrajectory<class principia::geometry::Frame<enum principia::serialization::Frame_PluginTag,7,1> >::WriteToMessage
I0121 16:20:56.725719  3572 continuous_trajectory_body.hpp:224] this: 129D6A68
I0121 16:20:56.725719  3572 continuous_trajectory_body.hpp:225] message->SpaceUsed(): 2724
I0121 16:20:56.726719  3572 continuous_trajectory_body.hpp:226] message->ByteSize(): 561
I0121 16:20:56.726719  3572 continuous_trajectory_body.hpp:201] principia::physics::ContinuousTrajectory<class principia::geometry::Frame<enum principia::serialization::Frame_PluginTag,7,1> >::WriteToMessage
I0121 16:20:56.726719  3572 continuous_trajectory_body.hpp:224] this: 129D6AB0
I0121 16:20:56.726719  3572 continuous_trajectory_body.hpp:225] message->SpaceUsed(): 3988
I0121 16:20:56.726719  3572 continuous_trajectory_body.hpp:226] message->ByteSize(): 809
I0121 16:20:56.726719  3572 continuous_trajectory_body.hpp:201] principia::physics::ContinuousTrajectory<class principia::geometry::Frame<enum principia::serialization::Frame_PluginTag,7,1> >::WriteToMessage
I0121 16:20:56.726719  3572 continuous_trajectory_body.hpp:224] this: 129D6AF8
I0121 16:20:56.726719  3572 continuous_trajectory_body.hpp:225] message->SpaceUsed(): 4604
I0121 16:20:56.726719  3572 continuous_trajectory_body.hpp:226] message->ByteSize(): 933
I0121 16:20:56.726719  3572 continuous_trajectory_body.hpp:201] principia::physics::ContinuousTrajectory<class principia::geometry::Frame<enum principia::serialization::Frame_PluginTag,7,1> >::WriteToMessage
I0121 16:20:56.726719  3572 continuous_trajectory_body.hpp:224] this: 129D6B40
I0121 16:20:56.726719  3572 continuous_trajectory_body.hpp:225] message->SpaceUsed(): 3988
I0121 16:20:56.726719  3572 continuous_trajectory_body.hpp:226] message->ByteSize(): 809
I0121 16:20:56.726719  3572 continuous_trajectory_body.hpp:201] principia::physics::ContinuousTrajectory<class principia::geometry::Frame<enum principia::serialization::Frame_PluginTag,7,1> >::WriteToMessage
I0121 16:20:56.726719  3572 continuous_trajectory_body.hpp:224] this: 129D6240
I0121 16:20:56.726719  3572 continuous_trajectory_body.hpp:225] message->SpaceUsed(): 3340
I0121 16:20:56.726719  3572 continuous_trajectory_body.hpp:226] message->ByteSize(): 685
I0121 16:20:56.726719  3572 continuous_trajectory_body.hpp:201] principia::physics::ContinuousTrajectory<class principia::geometry::Frame<enum principia::serialization::Frame_PluginTag,7,1> >::WriteToMessage
I0121 16:20:56.726719  3572 continuous_trajectory_body.hpp:224] this: 129D6480
I0121 16:20:56.726719  3572 continuous_trajectory_body.hpp:225] message->SpaceUsed(): 3340
I0121 16:20:56.726719  3572 continuous_trajectory_body.hpp:226] message->ByteSize(): 685
I0121 16:20:56.726719  3572 continuous_trajectory_body.hpp:201] principia::physics::ContinuousTrajectory<class principia::geometry::Frame<enum principia::serialization::Frame_PluginTag,7,1> >::WriteToMessage
I0121 16:20:56.726719  3572 continuous_trajectory_body.hpp:224] this: 129D63F0
I0121 16:20:56.726719  3572 continuous_trajectory_body.hpp:225] message->SpaceUsed(): 5220
I0121 16:20:56.726719  3572 continuous_trajectory_body.hpp:226] message->ByteSize(): 1057
I0121 16:20:56.726719  3572 continuous_trajectory_body.hpp:201] principia::physics::ContinuousTrajectory<class principia::geometry::Frame<enum principia::serialization::Frame_PluginTag,7,1> >::WriteToMessage
I0121 16:20:56.726719  3572 continuous_trajectory_body.hpp:224] this: 129D65A0
I0121 16:20:56.726719  3572 continuous_trajectory_body.hpp:225] message->SpaceUsed(): 5220
I0121 16:20:56.726719  3572 continuous_trajectory_body.hpp:226] message->ByteSize(): 1057
I0121 16:20:56.726719  3572 continuous_trajectory_body.hpp:201] principia::physics::ContinuousTrajectory<class principia::geometry::Frame<enum principia::serialization::Frame_PluginTag,7,1> >::WriteToMessage
I0121 16:20:56.726719  3572 continuous_trajectory_body.hpp:224] this: 129D6BD0
I0121 16:20:56.726719  3572 continuous_trajectory_body.hpp:225] message->SpaceUsed(): 5220
I0121 16:20:56.726719  3572 continuous_trajectory_body.hpp:226] message->ByteSize(): 1057
I0121 16:20:56.726719  3572 continuous_trajectory_body.hpp:201] principia::physics::ContinuousTrajectory<class principia::geometry::Frame<enum principia::serialization::Frame_PluginTag,7,1> >::WriteToMessage
I0121 16:20:56.726719  3572 continuous_trajectory_body.hpp:224] this: 129D6C18
I0121 16:20:56.726719  3572 continuous_trajectory_body.hpp:225] message->SpaceUsed(): 5220
I0121 16:20:56.726719  3572 continuous_trajectory_body.hpp:226] message->ByteSize(): 1057
I0121 16:20:56.726719  3572 continuous_trajectory_body.hpp:201] principia::physics::ContinuousTrajectory<class principia::geometry::Frame<enum principia::serialization::Frame_PluginTag,7,1> >::WriteToMessage
I0121 16:20:56.726719  3572 continuous_trajectory_body.hpp:224] this: 129D6C60
I0121 16:20:56.726719  3572 continuous_trajectory_body.hpp:225] message->SpaceUsed(): 4912
I0121 16:20:56.726719  3572 continuous_trajectory_body.hpp:226] message->ByteSize(): 995
I0121 16:20:56.726719  3572 continuous_trajectory_body.hpp:201] principia::physics::ContinuousTrajectory<class principia::geometry::Frame<enum principia::serialization::Frame_PluginTag,7,1> >::WriteToMessage
I0121 16:20:56.726719  3572 continuous_trajectory_body.hpp:224] this: 129D6CA8
I0121 16:20:56.726719  3572 continuous_trajectory_body.hpp:225] message->SpaceUsed(): 4604
I0121 16:20:56.726719  3572 continuous_trajectory_body.hpp:226] message->ByteSize(): 933
I0121 16:20:56.726719  3572 continuous_trajectory_body.hpp:201] principia::physics::ContinuousTrajectory<class principia::geometry::Frame<enum principia::serialization::Frame_PluginTag,7,1> >::WriteToMessage
I0121 16:20:56.726719  3572 continuous_trajectory_body.hpp:224] this: 129D6CF0
I0121 16:20:56.726719  3572 continuous_trajectory_body.hpp:225] message->SpaceUsed(): 5528
I0121 16:20:56.726719  3572 continuous_trajectory_body.hpp:226] message->ByteSize(): 1119
I0121 16:20:56.726719  3572 continuous_trajectory_body.hpp:201] principia::physics::ContinuousTrajectory<class principia::geometry::Frame<enum principia::serialization::Frame_PluginTag,7,1> >::WriteToMessage
I0121 16:20:56.726719  3572 continuous_trajectory_body.hpp:224] this: 129D6D38
I0121 16:20:56.726719  3572 continuous_trajectory_body.hpp:225] message->SpaceUsed(): 4296
I0121 16:20:56.726719  3572 continuous_trajectory_body.hpp:226] message->ByteSize(): 871
I0121 16:20:56.726719  3572 continuous_trajectory_body.hpp:201] principia::physics::ContinuousTrajectory<class principia::geometry::Frame<enum principia::serialization::Frame_PluginTag,7,1> >::WriteToMessage
I0121 16:20:56.726719  3572 continuous_trajectory_body.hpp:224] this: 129D6D80
I0121 16:20:56.726719  3572 continuous_trajectory_body.hpp:225] message->SpaceUsed(): 4296
I0121 16:20:56.726719  3572 continuous_trajectory_body.hpp:226] message->ByteSize(): 871
I0121 16:20:56.726719  3572 continuous_trajectory_body.hpp:201] principia::physics::ContinuousTrajectory<class principia::geometry::Frame<enum principia::serialization::Frame_PluginTag,7,1> >::WriteToMessage
I0121 16:20:56.726719  3572 continuous_trajectory_body.hpp:224] this: 129D6DC8
I0121 16:20:56.726719  3572 continuous_trajectory_body.hpp:225] message->SpaceUsed(): 2724
I0121 16:20:56.726719  3572 continuous_trajectory_body.hpp:226] message->ByteSize(): 561
I0121 16:20:56.726719  3572 continuous_trajectory_body.hpp:201] principia::physics::ContinuousTrajectory<class principia::geometry::Frame<enum principia::serialization::Frame_PluginTag,7,1> >::WriteToMessage
I0121 16:20:56.726719  3572 continuous_trajectory_body.hpp:224] this: 129D6E10
I0121 16:20:56.726719  3572 continuous_trajectory_body.hpp:225] message->SpaceUsed(): 2724
I0121 16:20:56.726719  3572 continuous_trajectory_body.hpp:226] message->ByteSize(): 561
I0121 16:20:56.726719  3572 ephemeris_body.hpp:377] message->SpaceUsed(): 95548
I0121 16:20:56.727720  3572 ephemeris_body.hpp:378] message->ByteSize(): 19570
I0121 16:20:56.727720  3572 physics_bubble.cpp:219] principia::ksp_plugin::PhysicsBubble::WriteToMessage
I0121 16:20:56.727720  3572 physics_bubble.cpp:266] message->SpaceUsed(): 40
I0121 16:20:56.727720  3572 physics_bubble.cpp:267] message->ByteSize(): 2
I0121 16:20:56.727720  3572 plugin.cpp:526] message->SpaceUsed(): 96348
I0121 16:20:56.727720  3572 plugin.cpp:527] message->ByteSize(): 19722
I0121 16:20:56.727720  3572 interface.cpp:676] principia::ksp_plugin::principia__DeletePluginSerialization
I0121 16:20:56.728719  3572 interface.cpp:644] principia::ksp_plugin::principia__SerializePlugin
I0121 16:20:56.728719  3572 interface.cpp:676] principia::ksp_plugin::principia__DeletePluginSerialization
I0121 16:20:56.742720  3572 interface.cpp:287] principia.ksp_plugin_adapter.PrincipiaPluginAdapter.OnDisable()
I0121 16:20:56.743721  3572 interface.cpp:313] Destroying Principia plugin
I0121 16:20:56.743721  3572 interface.cpp:319] Plugin destroyed
I0121 16:20:57.676774  3572 interface.cpp:202] Google logging was already initialized, no action taken
I0121 16:20:57.676774  3572 interface.cpp:287] principia.ksp_plugin_adapter.PrincipiaPluginAdapter.OnAwake()
I0121 16:20:57.718776  3572 interface.cpp:313] Destroying Principia plugin
I0121 16:20:57.718776  3572 interface.cpp:319] Plugin destroyed
I0121 16:20:57.718776  3572 interface.cpp:287] Serialization has 1 chunks
I0121 16:20:57.718776  3572 interface.cpp:287] serialization is 39444 characters long
I0121 16:20:57.718776  3572 interface.cpp:684] principia::ksp_plugin::principia__DeserializePlugin
I0121 16:20:57.719776  3572 interface.cpp:684] principia::ksp_plugin::principia__DeserializePlugin
I0121 16:20:57.719776  3760 plugin.cpp:532] principia::ksp_plugin::Plugin::ReadFromMessage
I0121 16:20:58.974848  3572 interface.cpp:644] principia::ksp_plugin::principia__SerializePlugin
I0121 16:20:58.974848  3572 plugin.cpp:477] principia::ksp_plugin::Plugin::WriteToMessage
I0121 16:20:58.974848  3572 ephemeris_body.hpp:362] principia::physics::Ephemeris<class principia::geometry::Frame<enum principia::serialization::Frame_PluginTag,7,1> >::WriteToMessage
I0121 16:20:58.974848  3572 continuous_trajectory_body.hpp:201] principia::physics::ContinuousTrajectory<class principia::geometry::Frame<enum principia::serialization::Frame_PluginTag,7,1> >::WriteToMessage
I0121 16:20:58.974848  3572 continuous_trajectory_body.hpp:224] this: 129D6AF8
I0121 16:20:58.974848  3572 continuous_trajectory_body.hpp:225] message->SpaceUsed(): 2724
I0121 16:20:58.974848  3572 continuous_trajectory_body.hpp:226] message->ByteSize(): 561
I0121 16:20:58.974848  3572 continuous_trajectory_body.hpp:201] principia::physics::ContinuousTrajectory<class principia::geometry::Frame<enum principia::serialization::Frame_PluginTag,7,1> >::WriteToMessage
I0121 16:20:58.974848  3572 continuous_trajectory_body.hpp:224] this: 129D6DC8
I0121 16:20:58.974848  3572 continuous_trajectory_body.hpp:225] message->SpaceUsed(): 3988
I0121 16:20:58.974848  3572 continuous_trajectory_body.hpp:226] message->ByteSize(): 809
I0121 16:20:58.974848  3572 continuous_trajectory_body.hpp:201] principia::physics::ContinuousTrajectory<class principia::geometry::Frame<enum principia::serialization::Frame_PluginTag,7,1> >::WriteToMessage
I0121 16:20:58.974848  3572 continuous_trajectory_body.hpp:224] this: 129D6BD0
I0121 16:20:58.974848  3572 continuous_trajectory_body.hpp:225] message->SpaceUsed(): 4604
I0121 16:20:58.974848  3572 continuous_trajectory_body.hpp:226] message->ByteSize(): 933
I0121 16:20:58.974848  3572 continuous_trajectory_body.hpp:201] principia::physics::ContinuousTrajectory<class principia::geometry::Frame<enum principia::serialization::Frame_PluginTag,7,1> >::WriteToMessage
I0121 16:20:58.974848  3572 continuous_trajectory_body.hpp:224] this: 129D6CA8
I0121 16:20:58.974848  3572 continuous_trajectory_body.hpp:225] message->SpaceUsed(): 3988
I0121 16:20:58.974848  3572 continuous_trajectory_body.hpp:226] message->ByteSize(): 809
I0121 16:20:58.974848  3572 continuous_trajectory_body.hpp:201] principia::physics::ContinuousTrajectory<class principia::geometry::Frame<enum principia::serialization::Frame_PluginTag,7,1> >::WriteToMessage
I0121 16:20:58.974848  3572 continuous_trajectory_body.hpp:224] this: 129D6D80
I0121 16:20:58.974848  3572 continuous_trajectory_body.hpp:225] message->SpaceUsed(): 3340
I0121 16:20:58.974848  3572 continuous_trajectory_body.hpp:226] message->ByteSize(): 685
I0121 16:20:58.974848  3572 continuous_trajectory_body.hpp:201] principia::physics::ContinuousTrajectory<class principia::geometry::Frame<enum principia::serialization::Frame_PluginTag,7,1> >::WriteToMessage
I0121 16:20:58.974848  3572 continuous_trajectory_body.hpp:224] this: 129D6CF0
I0121 16:20:58.974848  3572 continuous_trajectory_body.hpp:225] message->SpaceUsed(): 3340
I0121 16:20:58.974848  3572 continuous_trajectory_body.hpp:226] message->ByteSize(): 685
I0121 16:20:58.974848  3572 continuous_trajectory_body.hpp:201] principia::physics::ContinuousTrajectory<class principia::geometry::Frame<enum principia::serialization::Frame_PluginTag,7,1> >::WriteToMessage
I0121 16:20:58.974848  3572 continuous_trajectory_body.hpp:224] this: 129D6E10
I0121 16:20:58.974848  3572 continuous_trajectory_body.hpp:225] message->SpaceUsed(): 5220
I0121 16:20:58.974848  3572 continuous_trajectory_body.hpp:226] message->ByteSize(): 1057
I0121 16:20:58.974848  3572 continuous_trajectory_body.hpp:201] principia::physics::ContinuousTrajectory<class principia::geometry::Frame<enum principia::serialization::Frame_PluginTag,7,1> >::WriteToMessage
I0121 16:20:58.974848  3572 continuous_trajectory_body.hpp:224] this: 129D6AB0
I0121 16:20:58.974848  3572 continuous_trajectory_body.hpp:225] message->SpaceUsed(): 5220
I0121 16:20:58.974848  3572 continuous_trajectory_body.hpp:226] message->ByteSize(): 1057
I0121 16:20:58.974848  3572 continuous_trajectory_body.hpp:201] principia::physics::ContinuousTrajectory<class principia::geometry::Frame<enum principia::serialization::Frame_PluginTag,7,1> >::WriteToMessage
I0121 16:20:58.974848  3572 continuous_trajectory_body.hpp:224] this: 129D65A0
I0121 16:20:58.974848  3572 continuous_trajectory_body.hpp:225] message->SpaceUsed(): 5220
I0121 16:20:58.975848  3572 continuous_trajectory_body.hpp:226] message->ByteSize(): 1057
I0121 16:20:58.975848  3572 continuous_trajectory_body.hpp:201] principia::physics::ContinuousTrajectory<class principia::geometry::Frame<enum principia::serialization::Frame_PluginTag,7,1> >::WriteToMessage
I0121 16:20:58.975848  3572 continuous_trajectory_body.hpp:224] this: 129D6240
I0121 16:20:58.975848  3572 continuous_trajectory_body.hpp:225] message->SpaceUsed(): 5220
I0121 16:20:58.975848  3572 continuous_trajectory_body.hpp:226] message->ByteSize(): 1057
I0121 16:20:58.975848  3572 continuous_trajectory_body.hpp:201] principia::physics::ContinuousTrajectory<class principia::geometry::Frame<enum principia::serialization::Frame_PluginTag,7,1> >::WriteToMessage
I0121 16:20:58.975848  3572 continuous_trajectory_body.hpp:224] this: 129D6B40
I0121 16:20:58.975848  3572 continuous_trajectory_body.hpp:225] message->SpaceUsed(): 4912
I0121 16:20:58.975848  3572 continuous_trajectory_body.hpp:226] message->ByteSize(): 995
I0121 16:20:58.975848  3572 continuous_trajectory_body.hpp:201] principia::physics::ContinuousTrajectory<class principia::geometry::Frame<enum principia::serialization::Frame_PluginTag,7,1> >::WriteToMessage
I0121 16:20:58.975848  3572 continuous_trajectory_body.hpp:224] this: 129D6480
I0121 16:20:58.975848  3572 continuous_trajectory_body.hpp:225] message->SpaceUsed(): 4604
I0121 16:20:58.975848  3572 continuous_trajectory_body.hpp:226] message->ByteSize(): 933
I0121 16:20:58.975848  3572 continuous_trajectory_body.hpp:201] principia::physics::ContinuousTrajectory<class principia::geometry::Frame<enum principia::serialization::Frame_PluginTag,7,1> >::WriteToMessage
I0121 16:20:58.975848  3572 continuous_trajectory_body.hpp:224] this: 129D6D38
I0121 16:20:58.975848  3572 continuous_trajectory_body.hpp:225] message->SpaceUsed(): 5528
I0121 16:20:58.975848  3572 continuous_trajectory_body.hpp:226] message->ByteSize(): 1119
I0121 16:20:58.975848  3572 continuous_trajectory_body.hpp:201] principia::physics::ContinuousTrajectory<class principia::geometry::Frame<enum principia::serialization::Frame_PluginTag,7,1> >::WriteToMessage
I0121 16:20:58.975848  3572 continuous_trajectory_body.hpp:224] this: 129D6A68
I0121 16:20:58.975848  3572 continuous_trajectory_body.hpp:225] message->SpaceUsed(): 4296
I0121 16:20:58.975848  3572 continuous_trajectory_body.hpp:226] message->ByteSize(): 871
I0121 16:20:58.975848  3572 continuous_trajectory_body.hpp:201] principia::physics::ContinuousTrajectory<class principia::geometry::Frame<enum principia::serialization::Frame_PluginTag,7,1> >::WriteToMessage
I0121 16:20:58.975848  3572 continuous_trajectory_body.hpp:224] this: 129D6C60
I0121 16:20:58.975848  3572 continuous_trajectory_body.hpp:225] message->SpaceUsed(): 4296
I0121 16:20:58.975848  3572 continuous_trajectory_body.hpp:226] message->ByteSize(): 871
I0121 16:20:58.975848  3572 continuous_trajectory_body.hpp:201] principia::physics::ContinuousTrajectory<class principia::geometry::Frame<enum principia::serialization::Frame_PluginTag,7,1> >::WriteToMessage
I0121 16:20:58.975848  3572 continuous_trajectory_body.hpp:224] this: 129D6C18
I0121 16:20:58.975848  3572 continuous_trajectory_body.hpp:225] message->SpaceUsed(): 2724
I0121 16:20:58.975848  3572 continuous_trajectory_body.hpp:226] message->ByteSize(): 561
I0121 16:20:58.975848  3572 continuous_trajectory_body.hpp:201] principia::physics::ContinuousTrajectory<class principia::geometry::Frame<enum principia::serialization::Frame_PluginTag,7,1> >::WriteToMessage
I0121 16:20:58.975848  3572 continuous_trajectory_body.hpp:224] this: 129D6E58
I0121 16:20:58.975848  3572 continuous_trajectory_body.hpp:225] message->SpaceUsed(): 2724
I0121 16:20:58.975848  3572 continuous_trajectory_body.hpp:226] message->ByteSize(): 561
I0121 16:20:58.975848  3572 ephemeris_body.hpp:377] message->SpaceUsed(): 95548
I0121 16:20:58.975848  3572 ephemeris_body.hpp:378] message->ByteSize(): 19570
I0121 16:20:58.975848  3572 physics_bubble.cpp:219] principia::ksp_plugin::PhysicsBubble::WriteToMessage
I0121 16:20:58.975848  3572 physics_bubble.cpp:266] message->SpaceUsed(): 40
I0121 16:20:58.975848  3572 physics_bubble.cpp:267] message->ByteSize(): 2
I0121 16:20:58.975848  3572 plugin.cpp:526] message->SpaceUsed(): 96348
I0121 16:20:58.975848  3572 plugin.cpp:527] message->ByteSize(): 19722
I0121 16:20:58.976848  3572 interface.cpp:676] principia::ksp_plugin::principia__DeletePluginSerialization
I0121 16:20:58.976848  3572 interface.cpp:644] principia::ksp_plugin::principia__SerializePlugin
I0121 16:20:58.976848  3572 interface.cpp:676] principia::ksp_plugin::principia__DeletePluginSerialization
    @   55639399  	principia__SayHello [0x55639398+360744]
    @   5562456F  	principia__SayHello [0x5562456E+275198]
    @   55619EEA  	principia__SayHello [0x55619EE9+232569]
    @   5561B757  	principia__SayHello [0x5561B756+238822]
    @   55611F18  	principia__SayHello [0x55611F17+199847]
    @   5560F20C  	principia__SayHello [0x5560F20B+188315]
    @   556031B5  	principia__SayHello [0x556031B4+139076]
    @   555DF891  	principia__AdvanceTime [0x555DF890+80]
F0121 16:28:05.321233  3572 continuous_trajectory_body.hpp:346] Check failed: adjusted_tolerance_ < 1E6 * previous_adjusted_tolerance (+4.68287410098741093e+04 m vs. +1.00000000000000000e+03 m) Apocalypse occurred at +1.69560000000000000e+07 s, displacements are: {-3.49282603493174896e+10 m, +5.66270442741824417e+10 m, +1.43051734805826998e+09 m} {-3.49428985324578476e+10 m, +5.66261467240134583e+10 m, +1.43084853793783784e+09 m} {-3.49597231853022461e+10 m, +5.66240393730811310e+10 m, +1.43119247203491139e+09 m} {-3.49788863817104568e+10 m, +5.66196378825821075e+10 m, +1.43152237126945400e+09 m} {-3.49999793862095261e+10 m, +5.66107069127586975e+10 m, +1.43176777642360210e+09 m} {-3.50188619460542221e+10 m, +5.65935700674574738e+10 m, +1.43173955825286674e+09 m} {-3.50259985927999115e+10 m, +5.65730800483603821e+10 m, +1.43137054644079947e+09 m} {-3.50262614038773346e+10 m, +5.65595973268191986e+10 m, +1.43105020887789512e+09 m} {-3.50265505617097855e+10 m, +5.65518144973518982e+10 m, +1.43088812100199819e+09 m}, velocities are: {-5.03978634235681693e+03 m s^-1, -1.91513581246612659e+02 m s^-1, +1.18492526299651161e+02 m s^-1} {-5.81446760667980925e+03 m s^-1, -5.09221571312949607e+02 m s^-1, +1.26076469774440866e+02 m s^-1} {-6.65961692321701958e+03 m s^-1, -1.11486491197068221e+03 m s^-1, +1.27185009981394998e+02 m s^-1} {-7.52393606363402432e+03 m s^-1, -2.27493487743853575e+03 m s^-1, +1.13363830316464728e+02 m s^-1} {-7.90851250851699842e+03 m s^-1, -4.61011615100001836e+03 m s^-1, +5.69080769451357895e+01 m s^-1} {-5.19615554957706809e+03 m s^-1, -7.87950004670211638e+03 m s^-1, -9.07954216595477277e+01 m s^-1} {-6.82336758704137537e+02 m s^-1, -6.44296536649921109e+03 m s^-1, -1.46383434097063969e+02 m s^-1} {+8.47900445473596847e+01 m s^-1, -3.74178890429303920e+03 m s^-1, -8.78588688817521160e+01 m s^-1} {-3.71639892904535429e+02 m s^-1, -2.17278492760479230e+03 m s^-1, -3.48071394102201950e+01 m s^-1}
```

**Comment by eggrobin** [comment]
The log is from Bourbaki (`2015081515-Bourbaki-0-g6caa4a80b44ba7f9a030d79c558e4f8b1d051d6f`, not Brouwer; it is the known issue #631 that was fixed in Brouwer.
Additionally, this log is from the twenty-first of January, and has nothing to do with the subject of the issue "no plot of the trajectory".
If you have recently installed Brouwer and are not getting any logs (nor seeing the principia UI and trajectories), a mistake was probably made while installing.

**Comment by tuffzinator** [comment]
whoops, definitely the wrong file. sorry. but still cant see the trajectories since bourbaki.

**Comment by eggrobin** [comment]
The issue was resolved on IRC and was a misunderstanding about the behaviour of the plugin when in the atmosphere; we do not draw trajectories for vessels inside the atmosphere.
